In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
pd.__version__

'3.0.6'

In [6]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [7]:
print(df.head())

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4   
1        2008  Europe    Diesel  Front-wheel drive          4   
2        1996    Asia  Gasoline  Front-wheel drive          5   
3        1989  Europe  Gasoline  Front-wheel drive          4   
4        1994     USA    Diesel  Front-wheel drive          3   

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870   
1                 2390              6       272.0            4210   
2                 2320              6       267.0            4240   
3                 2130              6       258.0            4490   
4                 2580              7       304.0            4510   

   acceleration  fuel_efficiency_mpg  
0           NaN                 31.9  
1           NaN                 31.3  
2          17.3                 27.5  
3          18.7                 28.5  

In [8]:
row_count = len(df)

In [9]:
print(row_count)

10000


In [10]:
# Count total unique values in col 'fuel_type'
total_unique_fuel_types = df['fuel_type'].nunique()
print(total_unique_fuel_types)

3


In [11]:
# Returns a Series with the count of missing values for each column
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [12]:
# Returns MAX 'fuel_efficiency_mpg' for all cars manufactured in Asia
max_fuel_efficiency_value_asia = df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()
print(max_fuel_efficiency_value_asia)

41.2


In [13]:
# Q6. Median value of horsepower
median_value_hp = df['horsepower'].median()
print(median_value_hp)

254.0


In [14]:
# find the most frequent occurring value in the 'horsepower' column
most_frequent_hp = df['horsepower'].mode()[0]
print(most_frequent_hp)

252.0


In [15]:
# Fill missing values in the 'horsepower' column with the most frequent occuring value
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [16]:
# recalculate the median value of the 'horsepower' col
median_value_hp = df['horsepower'].median()
print(median_value_hp)

252.0


In [17]:
# Q7 Sum of weights
# select all cars from Asia
df_filtered_cars_asia = df.loc[df['origin'] == 'Asia']


In [18]:
# Select only cols 'vehicle_weight' & 'model_year'
df_subset_cols_vh_weight_model_year = df_filtered_cars_asia[['vehicle_weight', 'model_year']]
print(df_subset_cols_vh_weight_model_year)


      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]


In [20]:
X = df_subset_cols_vh_weight_model_year.head(7).to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [23]:
# Multiply the matrix X with its transpose
XTX = X.T.dot(X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [31]:
# Invert the df XTX
XTX_inverted = np.linalg.pinv(XTX)
print(XTX_inverted)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [32]:
# Create a pandas ExtensionArray
y = pd.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

<IntegerArray>
[1100, 1300, 800, 900, 1000, 1100, 1200]
Length: 7, dtype: Int64


In [33]:
X.shape

(7, 2)

In [34]:
#Product of inverse of XTX and X.T
w = XTX_inverted.dot(X.T)
print(w)

[[-2.50082897e-04 -1.65786806e-05 -2.86196661e-04  3.99964853e-04
  -1.18162927e-03  1.10298508e-03  2.25354894e-04]
 [ 6.12974614e-04  1.06954785e-04  6.91249245e-04 -7.95968736e-04
   2.63152339e-03 -2.31749941e-03 -4.16221392e-04]]


In [35]:
w_sum = sum(w)
print(w_sum)

[ 3.62891717e-04  9.03761040e-05  4.05052584e-04 -3.96003883e-04
  1.44989413e-03 -1.21451433e-03 -1.90866498e-04]


In [38]:
# X_transposed_df = pd.DataFrame(X.T)
# print(X_transposed_df)


In [39]:
# mm_mult = X_transposed_df.dot(XTX_inverted)
# print(mm_mult)

In [ ]:
# w = mm_mult*y
# print(w)

                 0                1                2                3  \
0  748801105448000  896638353468000  543575618608000  633047271516000   
1  344908455654400  413001571330400  250378941702400  291585150244800   

                 4                5                6  
0  643130889060000  824495976898000  851802175224000  
1  296243928968000  379760670194400  392346859267200  
