In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10,3.33)

array([3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33])

In [5]:
a = np.array([2,-1,4,9,12])
a

array([ 2, -1,  4,  9, 12])

In [6]:
a[0]
a[4]

np.int64(12)

In [7]:
a[2]

np.int64(4)

In [8]:
a[1] = 27

In [9]:
a

array([ 2, 27,  4,  9, 12])

In [ ]:
b = np.arange(3,10)
b

In [ ]:
c = np.linspace(0,100,11)
c


In [ ]:
d_2d = np.zeros((5,2))
d_2d

In [ ]:
>>> n = np.array([
...     [1, 2, 3],
...     [4, 5, 6],
...     [7, 8, 9]
... ])

In [ ]:
n

In [ ]:
n[0,1]

In [ ]:
n[2,1]

In [ ]:
n[2,2] = 99
n

In [ ]:
n[1]


In [ ]:
n[2] = [3,3,3]
n

In [ ]:
n[:0] = [20,5,1]
n

In [ ]:
n[:,0]

In [ ]:
n[:,0] = [20,5,1]
n

In [ ]:
# Generating random arrays
d = np.random.rand(5,2)
d

In [ ]:
np.random.seed(2)
dd = 100 * np.random.rand(5, 2)
dd

In [ ]:
# sample numbers from standard normal distribution
np.random.seed(2)
np.random.randn(5, 2)

In [ ]:
# `randint` for generating random integer numbers
np.random.seed(2)
e = np.random.randint(low=0,high=100,size=(5,2))
e

In [ ]:
# element-wise operations
a = np.arange(5)
a

In [ ]:
a + 1


In [ ]:
a * 2

In [ ]:
b = (10 + (a * 2)) ** 2 / 100
b

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
a >= 2

In [ ]:
a > b

In [ ]:
a[a > b]

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
n.min()

In [56]:
n

array([[20,  2,  3],
       [ 5,  5,  6],
       [ 1,  3,  3]])

In [10]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [11]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [12]:
v = np.array([1,0,0,2])

In [13]:
u_dot_v = vector_vector_multiplication(u,v)
u_dot_v

np.float64(14.0)

In [14]:
u.dot(v)

np.int64(14)

In [15]:
# Matrix-vector multiplication
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [16]:
U.shape

(3, 4)

In [17]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [18]:
v

array([1, 0, 0, 2])

In [19]:
v = np.array([1,0.5,2,1])

In [20]:
v.shape

(4,)

In [21]:
result_matrix_vector_mult = matrix_vector_multiplication(U,v)
result_matrix_vector_mult


array([20. ,  6. ,  8.5])

In [22]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [24]:
# matrix-matrix multiplication
V = np.array([
     [1, 1, 2],
     [0, 0.5, 1], 
     [0, 2, 1],
     [2, 1, 0],
 ])

In [25]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [26]:
U.shape

(3, 4)

In [27]:
V.shape

(4, 3)

In [28]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
U.dot(V) # using NumPy

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [30]:
# Identify matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [32]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [33]:
Vs = V[[0, 1, 2]]

In [34]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [35]:
Vs_inv = np.linalg.inv(Vs)

In [36]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [38]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])