In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10,3.33)

array([3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33, 3.33])

In [8]:
a = np.array([2,-1,4,9,12])
a

array([ 2, -1,  4,  9, 12])

In [9]:
a[0]
a[4]

np.int64(12)

In [10]:
a[2]

np.int64(4)

In [11]:
a[1] = 27

In [12]:
a

array([ 2, 27,  4,  9, 12])

In [14]:
b = np.arange(3,10)
b

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
c = np.linspace(0,100,11)
c


array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [18]:
d_2d = np.zeros((5,2))
d_2d

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
>>> n = np.array([
...     [1, 2, 3],
...     [4, 5, 6],
...     [7, 8, 9]
... ])

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
n[0,1]

np.int64(2)

In [23]:
n[2,1]

np.int64(8)

In [24]:
n[2,2] = 99
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [25]:
n[1]


array([4, 5, 6])

In [26]:
n[2] = [3,3,3]
n

array([[1, 2, 3],
       [4, 5, 6],
       [3, 3, 3]])

In [27]:
n[:0] = [20,5,1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [3, 3, 3]])

In [28]:
n[:,0]

array([1, 4, 3])

In [29]:
n[:,0] = [20,5,1]
n

array([[20,  2,  3],
       [ 5,  5,  6],
       [ 1,  3,  3]])

In [30]:
# Generating random arrays
d = np.random.rand(5,2)
d

array([[0.64380953, 0.43368235],
       [0.1634735 , 0.67393352],
       [0.75114422, 0.02320307],
       [0.2157792 , 0.0666001 ],
       [0.28478814, 0.14609105]])

In [32]:
np.random.seed(2)
dd = 100 * np.random.rand(5, 2)
dd

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [33]:
# sample numbers from standard normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [39]:
# `randint` for generating random integer numbers
np.random.seed(2)
e = np.random.randint(low=0,high=100,size=(5,2))
e

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [40]:
# element-wise operations
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a + 1


array([1, 2, 3, 4, 5])

In [42]:
a * 2

array([0, 2, 4, 6, 8])

In [43]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [44]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [45]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [46]:
a >= 2

array([False, False,  True,  True,  True])

In [47]:
a > b

array([False, False,  True,  True,  True])

In [48]:
a[a > b]

array([2, 3, 4])

In [50]:
a.min()

np.int64(0)

In [51]:
a.max()

np.int64(4)

In [52]:
a.sum()

np.int64(10)

In [53]:
a.mean()

np.float64(2.0)

In [54]:
a.std()

np.float64(1.4142135623730951)

In [55]:
n.min()

np.int64(1)

In [56]:
n

array([[20,  2,  3],
       [ 5,  5,  6],
       [ 1,  3,  3]])

In [57]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [58]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [59]:
v = np.array([1,0,0,2])

In [61]:
u_dot_v = vector_vector_multiplication(u,v)
u_dot_v

np.float64(14.0)

In [62]:
u.dot(v)

np.int64(14)

In [66]:
# Matrix-vector multiplication
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [65]:
U.shape

(3, 4)

In [67]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [68]:
v

array([1, 0, 0, 2])

In [4]:
v = np.array([1,0.5,2,1])

In [5]:
v.shape

(4,)